baseurl = "http://words.veldhousen.ninja"
languageCode = "en-us"
title = "Ramblings"
disqusShortname = "wordsveldhousen"
copyright="Adam Veldhousen"

[params]
  Author = "Adam Veldhousen"
  Description = "Guns, Code, Beer, Pictures"
  FirstName = "Adam"
  LastName = "Veldhousen"
  Twitter = "@adamveld12"
