baseurl = "http://words.veldhousen.ninja"
languageCode = "en-us"
title = "Posts and Stuff"
DisqusShortname = "wordsveldhousen"

[params]
  Copyright = "Adam V"
  Description = "Guns, Code, Beer, Pictures"
  Author = "Adam Veldhousen"

